apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: restic-cache
  namespace: consul
spec:
  storageClassName: longhorn
  resources:
    requests:
      storage: 100Mi
  accessModes:
    - ReadWriteOnce