apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"prometheus.io/port":"9090","prometheus.io/scrape":"true"},"name":"prometheus-service","namespace":"monitoring"},"spec":{"ports":[{"nodePort":30003,"port":8080,"targetPort":9090}],"selector":{"app":"prometheus-server"},"type":"NodePort"}}
    prometheus.io/port: "9090"
    prometheus.io/scrape: "true"
  creationTimestamp: "2020-11-17T05:47:56Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
          f:prometheus.io/port: {}
          f:prometheus.io/scrape: {}
      f:spec:
        f:externalTrafficPolicy: {}
        f:ports:
          .: {}
          k:{"port":8080,"protocol":"TCP"}:
            .: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
        f:selector:
          .: {}
          f:app: {}
        f:sessionAffinity: {}
        f:type: {}
    manager: kubectl-client-side-apply
    operation: Update
    time: "2020-11-17T05:47:56Z"
  name: prometheus-service
  namespace: monitoring
  resourceVersion: "7901"
  selfLink: /api/v1/namespaces/monitoring/services/prometheus-service
  uid: 9f40e4ff-f52a-4a98-82e4-70006af974ac
spec:
  clusterIP: 10.96.242.145
  externalTrafficPolicy: Cluster
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 9090
  selector:
    app: prometheus-server
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
