kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: bastion-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: v1
kind: Pod
metadata:
  name: bastion
spec:
  imagePullSecrets:
    - name: tz-registrykey
  containers:
  - name: bastion
    image: doohee323/devops-utils2:latest
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo $(date -u) >> /data/out.txt; sleep 5; done"]
    resources:
      requests:
        memory: "1000Mi"
        cpu: "1000m"
    volumeMounts:
    - name: persistent-storage
      mountPath: /data
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: bastion-pvc
#  nodeSelector:
#    team: devops
#    environment: dev
