apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: elasticsearch
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2020-12-22T00:31:43Z"
  labels:
    app: elasticsearch-master
    app.kubernetes.io/managed-by: Helm
    chart: elasticsearch
    heritage: Helm
    release: elasticsearch
  name: elasticsearch-master
  namespace: default
  resourceVersion: "51093"
spec:
  type: NodePort
  selector:
    app: elasticsearch-master
    chart: elasticsearch
    release: elasticsearch
  sessionAffinity: None
  ports:
  - name: http
    port: 9200
    protocol: TCP
    targetPort: 9200
    nodePort: 31200
  - name: transport
    port: 9300
    protocol: TCP
    targetPort: 9300
    nodePort: 31300
