apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: kibana
    meta.helm.sh/release-namespace: default
  labels:
    app: kibana
    app.kubernetes.io/managed-by: Helm
    heritage: Helm
    release: kibana
  name: kibana-kibana
  namespace: default
  resourceVersion: "56944"
spec:
  type: NodePort
  selector:
    app: kibana
    release: kibana
  sessionAffinity: None
  ports:
  - name: http
    port: 5601
    protocol: TCP
    targetPort: 5601
    nodePort: 30601
