####################################################################
## kafka-connector-target
####################################################################
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: postgres-pv-1
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv-1
spec:
  capacity:
    storage: 200Mi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: postgres-pv-1
  local:
#    path: /ubuntu/data/postgres-1     # can't use shared folder
    path: /home/topzone/data/postgres-1
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values: ["kube-master", "kube-node-1", "kube-node-2"]

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-postgres-target-pvc
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: postgres-pv-1
  resources:
    requests:
      storage: 100Mi

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-target-config
  labels:
    app: postgres
data:
  postgres_DB: postgres
  postgres_USER: postgres
  postgres_PASSWORD: admin1234!

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-target
  labels:
    app: postgres-target
spec:
  selector:
    matchLabels:
      app: postgres-target
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres-target
    spec:
      containers:
        - name: postgres-target
          image: postgres:10.4
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
          - configMapRef:
              name: postgres-target-config
          volumeMounts:
            - name: postgres-target-storage
              mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-target-storage
        persistentVolumeClaim:
          claimName: data-postgres-target-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: postgres-target
  labels:
    app: postgres-target
spec:
  selector:
    app: postgres-target
  ports:
  - port: 5432

