#apiVersion: argoproj.io/v1alpha1
#kind: Application
#metadata:
#  name: devops-dev-drillquiz
#  namespace: devops-dev
#spec:
#  destination:
#    namespace: devops-dev
#    server: https://kubernetes.default.svc
#  project: drillquiz
#  source:
#    directory:
#      jsonnet: {}
#      recurse: true
#    path: devops-dev-drillquiz
#    repoURL: https://github.com/doohee323/tz-argocd-repo.git
#

#argocd login argocd.drillquiz.com:443 --username admin --password ${admin_password} --insecure
#
#argocd app create devops-dev-drillquiz \
#  --project drillquiz \
#  --repo https://github.com/doohee323/tz-argocd-repo.git \
#  --path devops-dev-drillquiz/prod \
#  --dest-namespace drillquiz \
#  --dest-server https://kubernetes.default.svc --directory-recurse --upsert --grpc-web
#
#kubectl -n istio-system apply -f - <<EOF
#apiVersion: cert-manager.io/v1
#kind: Certificate
#metadata:
#  name: devops-dev-ssl
#  namespace: istio-system
#spec:
#  secretName: devops-dev-ssl
#  issuerRef:
#    kind: ClusterIssuer
#    name: letsencrypt-prod
#  commonName: devops.drillquiz.com
#  dnsNames:
#    - devops.drillquiz.com
#---
#EOF
