#apiVersion: argoproj.io/v1alpha1
#kind: Application
#metadata:
#  name: mc20-mc20-account
#  namespace: argocd
#spec:
#  destination:
#    namespace: mc20
#    server: https://kubernetes.default.svc
#  project: mc20
#  source:
#    directory:
#      jsonnet: {}
#      recurse: true
#    path: mc20-mc20-account
#    repoURL: https://bitbucket.org/seerslab/tz-argocd-repo.git


#argocd login argocd.default.drillquiz.com:443 --username admin --password ${admin_password} --insecure
#
#argocd app create mc20-mc20-account \
#  --project mc20 \
#  --repo https://bitbucket.org/seerslab/tz-argocd-repo.git \
#  --path mc20-mc20-account/prod \
#  --dest-namespace mc20 \
#  --dest-server https://kubernetes.default.svc --directory-recurse --upsert --grpc-web

#kubectl -n istio-system apply -f - <<EOF
#apiVersion: cert-manager.io/v1
#kind: Certificate
#metadata:
#  name: mc20-mc20-ssl
#  namespace: istio-system
#spec:
#  secretName: mc20-mc20-ssl
#  issuerRef:
#    kind: ClusterIssuer
#    name: letsencrypt-istio
#  commonName: prod.mc20.drillquiz.com
#  dnsNames:
#    - prod.mc20.drillquiz.com
#    - mc20.argear.io
#---
#EOF


kubectl -n istio-system apply -f - <<EOF
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mc20-mc20-dev-ssl
  namespace: istio-system
spec:
  secretName: mc20-mc20-dev-ssl
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-istio
  commonName: test1.mc20-dev.drillquiz.com
  dnsNames:
    - test1.mc20-dev.drillquiz.com
    - develop.mc20-dev.drillquiz.com
---
EOF
