apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-dev-drillquiz
spec:
  selector:
    matchLabels:
      app: devops-dev-drillquiz
  template:
    metadata:
      labels:
        org: tz
        team: drillquiz
        project: drillquiz
        environment: dev
        app: devops-dev-drillquiz
        version: develop-11
      annotations:
        instrumentation.opentelemetry.io/inject-nodejs: "true"
    spec:
      serviceAccountName: drillquiz-svcaccount
      containers:
        - name: devops-dev-drillquiz
          image: doohee323/drillquiz:836
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
#          readinessProbe:
#            httpGet:
#              path: /healthcheck
#              port: 8000
#          resources:
#            requests:
#              memory: "100Mi"
#              cpu: "100m"
#            limits:
#              memory: "500Mi"
#              cpu: "300m"
          envFrom:
            - configMapRef:
                name: devops-dev-drillquiz-configmap
            - secretRef:
                name: devops-dev-drillquiz-es
      nodeSelector:
        team: drillquiz
        environment: dev
        app_log: "true"
