---
apiVersion: v1
kind: ConfigMap
metadata:
  name: drillquiz-configmap-dev
data:
  ENVIRONMENT: "production"
  USE_DOCKER: "true"
  POSTGRES_DB: "drillquiz"
  POSTGRES_USER: "admin"
  POSTGRES_HOST: "devops-postgres-postgresql.devops-dev.svc.cluster.local"
  POSTGRES_PORT: "5432"
  SECRET_KEY: drillquiz-secret-dev
  CURRENT_DOMAIN: "devops.drillquiz.com"
  ALLOWED_HOSTS: "localhost,127.0.0.1,devops.drillquiz.com"
  CORS_ALLOWED_ORIGINS: "http://localhost:8080,https://devops.drillquiz.com"
  USE_MINIO: "true"
  MINIO_ENDPOINT: "http://minio.devops.svc.cluster.local:9000"
  MINIO_BUCKET_NAME: "devops-dev-drillquiz"
  GOOGLE_OAUTH_CLIENT_ID: "195449497097-rf2f22ampv4imqb80fvibhr7oq5oc7km.apps.googleusercontent.com"
  GOOGLE_OAUTH_REDIRECT_URI: "https://us-dev.drillquiz.com/api/google-oauth/"
  VUE_APP_GOOGLE_CLIENT_ID: "195449497097-rf2f22ampv4imqb80fvibhr7oq5oc7km.apps.googleusercontent.com"

---
apiVersion: v1
kind: Secret
metadata:
  name: drillquiz-secret-dev
type: Opaque
data:
  GOOGLE_OAUTH_CLIENT_SECRET: R09DU1BYLU45UWFueDlwRmFjNTNGYVdsQ2dVUFIxeFFUSXk=
  MINIO_ACCESS_KEY: UnFyR1ZxR0hDaEExZHE4cGc4dUI=
  MINIO_BUCKET_NAME: ZHJpbGxxdWl6LWRldg==
  MINIO_SECRET_KEY: SXFwUTZ6UFRZSm5IamVXY2VDdHhaRzhtN2hNbjcwSnZLU0w5OXV1cg==
  OPENAI_API_KEY: >-
    c2stcHJvai0wR0RvM09sRmNJYlNTNEQya25peUtldEQxaHcxUlYyOHFEeC1NUVZ4YzlkdTR6U2hlWTYxVnRreGRaUGRuQlNNVzhNdGwxV0VfYVQzQmxia0ZKSjVqM2l6ZEJtZG5lTXJxcTdqTmpwY1FlTU9Cd2YxVUhJTlRKNjFNNnlxQW1VOTN3dG5JRDNINHJOVzRvd1NuME1fQkhfcUw0OEE=
  POSTGRES_PASSWORD: RGV2T3BzITMyMw==
  SECRET_KEY: eW91ci1wcm9kdWN0aW9uLXNlY3JldC1rZXktaGVyZQ==
  USE_MINIO: dHJ1ZQ==

---
apiVersion: v1
kind: Service
metadata:
  name: devops-dev-drillquiz-sv
spec:
  type: NodePort
  selector:
    app: devops-dev-drillquiz
  ports:
    - port: 80
      name: api-80
      targetPort: 8000

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: devops-dev-drillquiz-ing
  annotations:
#    nginx.ingress.kubernetes.io/rewrite-target: /$2
#    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  rules:
  - host: devops1.drillquiz.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: devops-dev-drillquiz-sv
            port:
              number: 80
  tls:
    - hosts:
        - devops1.drillquiz.com
      secretName: devops-dev-drillquiz-ssl

---
kind: Gateway
apiVersion: networking.istio.io/v1alpha3
metadata:
  name: drillquiz-http-to-https
spec:
  servers:
  - hosts:
      - devops.drillquiz.com
      - sw.drillquiz.com
    port:
      name: http2
      number: 880
      protocol: HTTP2
    tls:
      httpsRedirect: false
  - hosts:
      - devops.drillquiz.com
      - sw.drillquiz.com
    port:
      number: 8443
      name: https-443
      protocol: HTTPS
    tls:
      credentialName: devops-dev-ssl
      mode: SIMPLE
      privateKey: sds
      serverCertificate: sds
  selector:
    istio: ingressgateway

---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: devops-dev-vs
spec:
  gateways:
  - drillquiz-http-to-https
  hosts:
  - devops.drillquiz.com
  - sw.drillquiz.com
  http:
  - name: devops-dev-drillquiz-vs
    match:
    - uri:
        prefix: /devops/
    - uri:
        prefix: /devops
    rewrite:
      uri: /
    route:
    - destination:
        host: devops-dev-drillquiz-sv.drillquiz.svc.cluster.local
  - name: devops-dev-sw-vs
    match:
    - uri:
        prefix: /sw/
    - uri:
        prefix: /sw
    rewrite:
      uri: /
    route:
    - destination:
        host: devops-dev-drillquiz-sv.drillquiz.svc.cluster.local

---

apiVersion: v1
kind: Service
metadata:
  name: istio-ingressgateway-proxy
spec:
  type: ExternalName
  externalName: istio-ingressgateway.istio-system.svc.cluster.local
  ports:
  - name: http
    port: 880
    targetPort: 880
    protocol: TCP
  - name: https
    port: 8443
    targetPort: 8443
    protocol: TCP

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: drillquiz-to-istio-proxy
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  ingressClassName: nginx
  rules:
  - host: devops.drillquiz.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: istio-ingressgateway-proxy
            port:
              number: 880
  - host: sw.drillquiz.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: istio-ingressgateway-proxy
            port:
              number: 880
  tls:
    - hosts:
        - devops.drillquiz.com
        - sw.drillquiz.com
      secretName: drillquiz.istio-system-tls1
