---
apiVersion: v1
kind: ConfigMap
metadata:
  name: devops-dev-drillquiz-configmap
data:
  GIT_BRANCH: argo-vault
  DB_HOSTNAME: host.docker.internal
  DB_R_HOSTNAME: host.docker.internal
---
apiVersion: v1
kind: Service
metadata:
  name: devops-dev-drillquiz-sv
spec:
  type: ClusterIP
  selector:
    app: devops-dev-drillquiz
  ports:
    - port: 80
      name: http-80
      targetPort: 8000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: devops-dev-drillquiz-ing
  annotations:
#    nginx.ingress.kubernetes.io/rewrite-target: /$2
#    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    kubernetes.io/ingress.class: "istio"
#    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  rules:
  - host: istio.drillquiz.com
    http:
      paths:
      - path: /account(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: devops-dev-drillquiz-sv
            port:
              number: 80
  tls:
  - hosts:
    - istio.drillquiz.com
    secretName: devops-dev-drillquiz-ssl

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: devops-dev-drillquiz-es
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: drillquiz-prod
    kind: SecretStore
  target:
    name: devops-dev-drillquiz-es
  dataFrom:
    - extract:
        key: secret/drillquiz-prod/drillquiz

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: devops-dev-drillquiz-ha
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: devops-dev-drillquiz
  minReplicas: 2
  maxReplicas: 20
  targetCPUUtilizationPercentage: 25

---
kind: Gateway
apiVersion: networking.istio.io/v1alpha3
metadata:
  name: drillquiz-http-to-https
spec:
  servers:
  - hosts:
      - istio.drillquiz.com
    port:
      name: http2
      number: 80
      protocol: HTTP2
    tls:
      httpsRedirect: false
  - hosts:
      - istio.drillquiz.com
    port:
      number: 443
      name: https-443
      protocol: HTTPS
    tls:
      credentialName: devops-dev-ssl
      mode: SIMPLE
      privateKey: sds
      serverCertificate: sds
  selector:
    istio: ingressgateway

---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: devops-dev-vs
spec:
  gateways:
    - drillquiz-http-to-https
  hosts:
    - istio.drillquiz.com
  http:
  - name: devops-dev-drillquiz-vs
    match:
    - uri:
        prefix: /account/
    - uri:
        prefix: /account
    rewrite:
      uri: /
    route:
    - destination:
        host: devops-dev-drillquiz-sv.drillquiz.svc.cluster.local
  - name: devops-dev-admin-vs
    match:
    - uri:
        prefix: /admin/
    - uri:
        prefix: /admin
    rewrite:
      uri: /
    route:
    - destination:
        host: devops-dev-admin-sv.drillquiz.svc.cluster.local

---

apiVersion: v1
kind: Service
metadata:
  name: istio-ingressgateway-proxy
  namespace: default
spec:
  type: ExternalName
  externalName: istio-ingressgateway.istio-system.svc.cluster.local
  ports:
  - name: http
    port: 880
    targetPort: 880
    protocol: TCP
  - name: https
    port: 8443
    targetPort: 8443
    protocol: TCP

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: drillquiz-to-istio-proxy
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  ingressClassName: nginx
  rules:
  - host: istio.drillquiz.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: istio-ingressgateway-proxy
            port:
              number: 880
  tls:
    - hosts:
        - istio.drillquiz.com
      secretName: drillquiz.istio-system-tls1
