apiVersion: v1
kind: Pod
metadata:
  name: tz-consul
spec:
  containers:
    - name: tz-consul
      image: 'consul:latest'
      command:
        - '/bin/sh'
        - '-ec'
        - |
          export CONSUL_HTTP_ADDR="192.168.1.10:8500"
          consul kv put hello world
  restartPolicy: Never

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: tz-consul-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tz-consul
  template:
    metadata:
      labels:
        app: tz-consul
    spec:
      containers:
        - name: tz-consul
          image: 'consul:latest'
          command:
            - '/bin/sh'
            - '-ec'
            - |
              export CONSUL_HTTP_ADDR="192.168.1.10:8500"
              consul kv put hello world
