global:
#  name: consul
  datacenter: tz-dc
  enabled: true

  gossipEncryption:
    secretName: "consul-gossip-encryption-key"
    secretKey: "key"

  tls:
    enabled: true
    enableAutoEncrypt: true
    verify: true

  acls:
    manageSystemACLs: true

ui:
  service:
    type: 'ClusterIP'

connectInject:
  enabled: true
# Enable CRD Controller
#controller:
#  enabled: true

client:
  enabled: true

server:
  replicas: 3
  storage: 100Mi
  connect: true
  disruptionBudget:
    enabled: true
    maxUnavailable: 0
  service:
    enabled: true
