# Choose an optional name for the datacenter
global:
  datacenter: tz-dc

# Enable the Consul Web UI via a NodePort
ui:
  service:
    type: 'ClusterIP'

# Enable Connect for secure communication between nodes
connectInject:
  enabled: true
# Enable CRD Controller
controller:
  enabled: true

client:
  enabled: true

# Use only one Consul server for local development
server:
  replicas: 3
  storage: 100Mi
  disruptionBudget:
    enabled: true
    maxUnavailable: 0
  service:
    enabled: true
