apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv
spec:
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.1.10
    path: /home/vagrant/data

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Mi

#---
#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  name: tz-nfs-pv
#spec:
#  capacity:
#    storage: 1Gi
#  accessModes:
#    - ReadWriteMany
#  nfs:
#    server: 192.168.0.143
#    path: /data
#
#---
#kind: PersistentVolumeClaim
#apiVersion: v1
#metadata:
#  name: tz-nfs-pv
#spec:
#  accessModes:
#    - ReadWriteMany
#  resources:
#    requests:
#      storage: 1Gi
