apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: tz-py-sync-job
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: tz-py-sync-job
            image: eeacms/rsync
            command: ["/bin/sh", "-ec", "/bin/sh /mnt/sync_json.sh; sleep 10;"]
#            command: ['sleep', '3000']
            volumeMounts:
              - name: local-persistent-storage
                mountPath: /mnt
          volumes:
            - name: local-persistent-storage
              persistentVolumeClaim:
                claimName: tz-pvc
          restartPolicy: OnFailure
