apiVersion: v1
kind: Secret
metadata:
  name: ui-tls
  namespace: consul
data:
  tls.crt: YOUR_CRT_IF_YOU_USE_TLS
  tls.key: YOUR_KEY_IF_YOU_USE_TLS
type: kubernetes.io/tls

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: vault
  namespace: consul
spec:
  rules:
    - host: "consul.localdev"
      http:
        paths:
          - backend:
              serviceName: vault-ui
              servicePort: ui
            path: /
  tls:
    - hosts:
      - "https-consul.localdev"
      secretName: ui-tls
