global:
#  name: consul
  datacenter: tz-dc
  enabled: true

  gossipEncryption:
    secretName: "consul-gossip-encryption-key"
    secretKey: "key"

  tls:
    enabled: true
    enableAutoEncrypt: true
    verify: true
    caCert:
      secretName: ""
      secretKey: ""
    caKey:
      secretName: ""
      secretKey: ""

  acls:
    manageSystemACLs: true
    bootstrapToken:
      secretName: ""
      secretKey: ""

ui:
  service:
    type: 'ClusterIP'

connectInject:
  enabled: true
# Enable CRD Controller
#controller:
#  enabled: true

client:
  enabled: true

server:
  replicas: 3
  storage: 100Mi
  connect: true
  disruptionBudget:
    enabled: true
    maxUnavailable: 0
  service:
    enabled: true
