- name: Update containerd config.toml and restart containerd service
  hosts: all
  become: yes
  tasks:
    - name: Copy config.toml to /etc/containerd/config.toml
      copy:
        src: ./config.toml
        dest: /etc/containerd/config.toml
        owner: root
        group: root
        mode: '0644'

    - name: Restart containerd service
      service:
        name: containerd
        state: restarted
