all:
  hosts:
    node1:
      ansible_host: 192.168.0.127
      ip: 192.168.0.127
      access_ip: 192.168.0.127
    node2:
      ansible_host: 192.168.0.128
      ip: 192.168.0.128
      access_ip: 192.168.0.128
    node3:
      ansible_host: 192.168.0.129
      ip: 192.168.0.129
      access_ip: 192.168.0.129
  children:
    kube-master:
      hosts:
        node1:
    kube-node:
      hosts:
        node2:
        node3:
    etcd:
      hosts:
        node1:
    k8s-cluster:
      children:
        kube-master:
        kube-node:
    calico-rr:
      hosts: {}
