all:
  hosts:
    kube-master:
      ansible_host: 192.168.0.127
      ip: 192.168.0.127
      access_ip: 192.168.0.127
    kube-node1:
      ansible_host: 192.168.0.128
      ip: 192.168.0.128
      access_ip: 192.168.0.128
    kube-node2:
      ansible_host: 192.168.0.129
      ip: 192.168.0.129
      access_ip: 192.168.0.129
  children:
    kube-master:
      hosts:
        kube-master:
    kube-node:
      hosts:
        kube-node1:
        kube-node2:
    etcd:
      hosts:
        kube-master:
    k8s-cluster:
      children:
        kube-master:
        kube-node:
    calico-rr:
      hosts: {}
