all:
  hosts:
    node1:
      ansible_host: 192.168.0.36
      ip: 192.168.0.36
      access_ip: 192.168.0.36
    node2:
      ansible_host: 192.168.1.12
      ip: 192.168.1.12
      access_ip: 192.168.1.12
    node3:
      ansible_host: 192.168.1.13
      ip: 192.168.1.13
      access_ip: 192.168.1.13
  children:
    kube-master:
      hosts:
        node1:
        node2:
    kube-node:
      hosts:
        node1:
        node2:
        node3:
    etcd:
      hosts:
        node1:
        node2:
        node3:
    k8s-cluster:
      children:
        kube-master:
        kube-node:
    calico-rr:
      hosts: {}
