all:
  hosts:
    k8s-master:
      ansible_host: 192.168.0.127
      ip: 192.168.0.127
      access_ip: 192.168.0.127
    k8s-node1:
      ansible_host: 192.168.0.128
      ip: 192.168.0.128
      access_ip: 192.168.0.128
    k8s-node2:
      ansible_host: 192.168.0.129
      ip: 192.168.0.129
      access_ip: 192.168.0.129
  children:
    k8s-master:
      hosts:
        k8s-master:
    kube-node:
      hosts:
        k8s-node1:
        k8s-node2:
    etcd:
      hosts:
        k8s-master:
    k8s-cluster:
      children:
        k8s-master:
        kube-node:
    calico-rr:
      hosts: {}
