kind: ConfigMap
apiVersion: v1
metadata:
  name: prometheus-grafana
data:
  grafana.ini: |
    [analytics]
    check_for_updates = true
    [grafana_net]
    url = https://grafana.net
    [log]
    mode = console
    [paths]
    data = /var/lib/grafana/data
    logs = /var/log/grafana
    plugins = /var/lib/grafana/plugins
    provisioning = /etc/grafana/provisioning
    [smtp]
    enabled = true
    host = smtp.gmail.com:587
    user = doohee323@gmail.com
    password = admin_password
    skip_verify = true
    from_address = doohee323@gmail.com
    from_name = Grafana (eks_project)
    ehlo_identity = grafana.default.eks_project.eks_domain
    [server]
    protocol = http
    domain = grafana.default.eks_project.eks_domain
    root_url = https://grafana.default.eks_project.eks_domain
    [users]
    viewers_can_edit = true
    [auth.google]
    enabled: true
    auto_login = false
    client_id = grafana_goauth2_client_id
    client_secret = grafana_goauth2_client_secret
    scopes = https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/userinfo.email
    auth_url = https://accounts.google.com/o/oauth2/auth
    token_url = https://oauth2.googleapis.com/token
    allowed_domains = shoptoolstest.co.kr
    allow_sigh_up = true
    hosted_domain = shoptoolstest.co.kr

---

kind: ConfigMap
apiVersion: v1
metadata:
  name: prometheus-kube-prometheus-grafana-datasource
data:
  datasource.yaml: |-
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://prometheus-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090
      access: proxy
      isDefault: true
    - name: Loki
      type: loki
      url: http://loki.monitoring.svc.cluster.local:3100/
      access: proxy
---

kind: ConfigMap
apiVersion: v1
metadata:
  name: loki-loki-stack
data:
  loki-stack-datasource.yaml: |-
    apiVersion: 1
    datasources:
    - name: Loki
      type: loki
      access: proxy
      url: http://loki.monitoring.svc.cluster.local:3100/
      version: 1

#---
#apiVersion: v1
#kind: Secret
#metadata:
#  name: prometheus-grafana
#  namespace: monitoring
#type: Opaque
#data:
#  admin-password: admin_password
