apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage0
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage1
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-pv0
spec:
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage0
  local:
    path: /vagrant/kafka/index0
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values: ["k8s-master", "node-1", "node-2"]

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-pv1
spec:
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage1
  local:
    path: /vagrant/kafka/index1
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values: ["k8s-master", "node-1", "node-2"]

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-bonah-kafka-0
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 2Gi
  storageClassName: local-storage0

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-bonah-zookeeper-0
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 2Gi
  storageClassName: local-storage1
