---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-bastion
spec:
  selector:
    matchLabels:
      app: devops-bastion
  replicas: 1
  template:
    metadata:
      labels:
        app: devops-bastion
    spec:
      containers:
      - name: devops-bastion
        image: ubuntu:22.04
        resources:
          requests:
            memory: "100Mi"
            cpu: "100m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        command: ["/bin/sh"]
        args: ["-c", "while true; do echo $(date -u) >> /data/out.txt; sleep 5; done"]
#      nodeSelector:
#        team: devops
#        environment: prod
